[[plugins]] # 日本語マニュアル
repo = 'vim-jp/vimdoc-ja'
hook_add = '''
    set helplang=ja
'''

[[plugins]] # 補完
repo = 'Shougo/deol.nvim'
hook_add = '''
    " 【Ctrl + p】 float windowでターミナルを表示
    nnoremap <silent><C-p> :<C-u>Deol -split=floating<CR>
    " 【ESC】 ターミナルモードから抜ける
    tnoremap <ESC>   <C-\><C-n>
'''

[[plugins]] # Codic
repo = 'koron/codic-vim'
on_cmd = 'Codic'

[[plugins]] # 翻訳
repo = 'skanehira/translate.vim'

[[plugins]] # Docker
repo = 'skanehira/docker.vim'

[[plugins]] # Emmet
repo = 'mattn/emmet-vim'
on_i = 1
hook_source = '''
  let g:user_emmet_mode = 'i'
  let g:user_emmet_leader_key='<C-E>'
  let g:use_emmet_complete_tag = 1
  let g:user_emmet_settings = {
    \'variables': {
    \  'lang': "ja"
    \},
    \'indentation': '  '
    \}
'''
[[plugins]] # Markdown
repo = 'mattn/vim-maketable'

[[plugins]] # EditorConfig
repo = 'editorconfig/editorconfig-vim'
on_path = '.*'

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_if = 1
on_event = 'TextYankPost'
on_source = ['denite.nvim']
